name: release

on:
  push:
    branches:
      - ghactions
  workflow_dispatch:
  workflow_call:

jobs:
  mac-arm64e-release:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build-mac
        with:
          rust-arch: aarch64
          lipo-arch: arm64e

  mac-x86_64-release:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build-mac
        with:
          rust-arch: x86_64
          lipo-arch: x86_64

  mac-arm64e-x86_64-release:
    runs-on: macos-13
    needs:
      - mac-arm64e-release
      - mac-x86_64-release
    steps:
      - name: Lipo
        uses: ./.github/actions/lipo-mac-arm64e+x86_64

  windows-x64-release:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build-windows
        with:
          rust-arch: x86_64
          ms-arch: x64
