name: release-mac

jobs:
  mac-aarch64-release:
    runs-on: macos-13-xlarge
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build-mac
        with:
          arch: aarch64

  mac-x86_64-release:
    runs-on: macos-13-xlarge
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build-mac
        with:
          arch: x86_64
                    
