name: release-mac

on:
  push:
    branches:
      - ghactions
  workflow_dispatch:
  workflow_call:

jobs:
  mac-x86_64-release:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build-mac
        with:
          arch: x86_64
                    
